### ISSUE TITLE
Add option to include / exclude specific genomic features during shuffeling

### ISSUE THREAD

**Issue by tjakobi** [dieterich-lab/circtools#27]
We need the possibility to select specific regions of the genome for shuffling.

I.e. current  mode is to shuffle over the complete genome.

New modes: 
- **all** (that's the current mode and will probably stay default)
- **CDS** the coding sequence
- any combination of 
  - **Exon**
  - **Intron**
  - **UTR**: untranslated regions

Whereas all exons + introns + UTR(s) should sum up to the hosting "gene" feature.

**Comment by tjakobi** [comment]
First working version pushed via commit effb77b.

**Comment by CDieterich** [comment]
Hi,

be careful with 
"Whereas Exon + Intron + UTR basically equals CDS."

This is not true. CDS never includes Introns and UTRs.

**Comment by tjakobi** [comment]
That's correct of course, I'll update the issue.
