### ISSUE TITLE
Integration of CircTest

### ISSUE THREAD

**Issue by tjakobi** [dieterich-lab/circtools#5]
This issues includes 
- a wrapper script from Python to R
- the interface between the R script and the Python framework

**Comment by CDieterich** [comment]
I noticed that Circ.test does not give the direction of change in the output table

Say, you compare RNAseR+ over mock treated, you would like to know if there is an enrichment in RNAseR+. However, this is not visible and only a p-value is given which could mean enrichment OR depletion

**Comment by tjakobi** [comment]
Direction of change has been implemented in the master tree of CircTest via commit https://github.com/dieterich-lab/CircTest/commit/eb162f1a522a8b063365cbe7d7c2fd6856fee434.
