### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by circR** [dieterich-lab/circtools#57]
Hi Sir
I tried to install circtools on my PC(ubuntu 16.04) and I got the following error message. Could you help with this?  Thank you

$ python3 setup.py install --verbose --user
running install
Requirement already satisfied: statsmodels in /home/cd/miniconda3/lib/python3.6/site-packages (0.9.0)
Requirement already satisfied: patsy in /home/cd/miniconda3/lib/python3.6/site-packages (from statsmodels) (0.5.0)
Requirement already satisfied: pandas in /home/cd/miniconda3/lib/python3.6/site-packages (from statsmodels) (0.23.0)
Requirement already satisfied: six in /home/cd/miniconda3/lib/python3.6/site-packages (from patsy->statsmodels) (1.11.0)
Requirement already satisfied: numpy>=1.4 in /home/cd/miniconda3/lib/python3.6/site-packages (from patsy->statsmodels) (1.14.3)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/cd/miniconda3/lib/python3.6/site-packages (from pandas->statsmodels) (2.7.3)
Requirement already satisfied: pytz>=2011k in /home/cd/miniconda3/lib/python3.6/site-packages (from pandas->statsmodels) (2018.4)
Bioconductor version 3.6 (BiocInstaller 1.28.0), ?biocLite for help
A new version of Bioconductor is available after installing the most recent
  version of R; see http://bioconductor.org/install
BioC_mirror: https://bioconductor.statistik.tu-dortmund.de
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.4 (2018-03-15).
installation path not writeable, unable to update packages: DBI, RMySQL,
  codetools, foreign, lattice, spatial
Skipping install of 'CircTest' from a github remote, the SHA1 (2fd16602) has not changed since last install.
  Use `force = TRUE` to force installation
Skipping install of 'primex' from a github remote, the SHA1 (f715f111) has not changed since last install.
  Use `force = TRUE` to force installation
Cloning into 'DCC'...
remote: Counting objects: 876, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 876 (delta 6), reused 17 (delta 4), pack-reused 857
Receiving objects: 100% (876/876), 226.95 KiB | 239.00 KiB/s, done.
Resolving deltas: 100% (599/599), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from setuptools import setup
ImportError: No module named setuptools
Cloning into 'FUCHS'...
remote: Counting objects: 1928, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1928 (delta 2), reused 7 (delta 1), pack-reused 1920
Receiving objects: 100% (1928/1928), 36.20 MiB | 4.58 MiB/s, done.
Resolving deltas: 100% (1024/1024), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from setuptools import setup
ImportError: No module named setuptools
Traceback (most recent call last):
  File "setup.py", line 234, in <module>
    'Documentation': 'http://docs.circ.tools'
  File "/home/cd/miniconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/cd/miniconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/cd/miniconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/cd/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 71, in run
    subprocess.check_call(["bash", "scripts/install_external.sh"])
  File "/home/cd/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', 'scripts/install_external.sh']' returned non-zero exit status 1.

**Comment by tjakobi** [comment]
Dear @circR,

it seems like you are using a conda environment which is not (yet) supported by circtools. 

```
Checking connectivity... done.
Traceback (most recent call last):
File "setup.py", line 11, in 
from setuptools import setup
ImportError: No module named setuptools
```

DCC and FUCHS both need Python2 and an installed setuptools package for this Python version. 

```
pip2 install setuptools
```

If that command fails due to permission errors you may try

```
pip2 install setuptools --user
```

This should install the required package. Afterwards the installation should continue normally.

**Comment by circR** [comment]
Hi Sir

Thank you very much. It worked for the installation after running the command you suggested. 
However, when I tried to use the primex mode, it failed again with the following message:

 $ circtools primex -d test.candidates -f ../WholeGenomeFasta/genome.fa -g ../WBce235/genes.gtf 
Start parsing GTF file
Start merging GTF file
extracting flanking exons for circRNA # 1 marc-4_I_285008_285638_+
Traceback (most recent call last):
  File "/home/cd/.local/bin/circtools", line 18, in <module>
    import circtools
  File "/home/cd/.local/lib/python3.6/site-packages/circtools/__init__.py", line 2, in <module>
    main()
  File "/home/cd/.local/lib/python3.6/site-packages/circtools/circtools.py", line 31, in main
    CircTools()
  File "/home/cd/.local/lib/python3.6/site-packages/circtools/circtools.py", line 76, in __init__
    getattr(self, args.command)()
  File "/home/cd/.local/lib/python3.6/site-packages/circtools/circtools.py", line 329, in primex
    primex_instance.run_module()
  File "/home/cd/.local/lib/python3.6/site-packages/circtools/primex/primex.py", line 212, in run_module
    if current_line[3] == "not_annotated":
IndexError: list index out of range


I used one candidate circRNA from DCC results as input.
Any suggestions? Thank you.

**Comment by tjakobi** [comment]
Are you supplying a file name or a directory as `-d` parameter? `-d` should specify the path to the `CircCoordinates` file produced by DCC.

**Comment by circR** [comment]
Yes, the command is like this:
$ circtools primex -d test.candidates -f ../WholeGenomeFasta/genome.fa -g ../WBce235/genes.gtf

The content of "test.candidates" is extracted from the CircCoordinates file from DCC output

Chr	Start	End	Gene	JunctionType	Strand	Start.End.Region	OverallRegion
I	285008	285638	marc-4	1	+	exon-exon	transcript,exon,CDS

**Comment by tjakobi** [comment]
Did you keep the tabs as column separators? circtools expects tab-separated columns in all  input and output files.

**Comment by circR** [comment]
Yes, the file is tab-separated. 
I used DCC to predict circRNAs in C. elegans. Does this matter? Because in the -o option, it seems only mouse and human are supported.

**Comment by tjakobi** [comment]
The species shouldn't matter, circtools stumbles over an ill-formatted DCC input file. 

Could you please execute the following command:

```
awk '{print $4}' test.candidates  | head
```

The -o option only refers to the optional BLASTING step that right now is only supported for human and mouse.

**Comment by circR** [comment]
![image](https://user-images.githubusercontent.com/34292024/44395998-8ae83d80-a576-11e8-9e40-ec9c31367099.png)

**Comment by tjakobi** [comment]
Could you please run the edited command:

```awk -F '\t' '{print $4}' test.candidates  | head```

**Comment by tjakobi** [comment]
Okay, it seems you have an additional new line at the end of the test.candidates files. Could you remove that empty line and run circtools again?

**Comment by circR** [comment]
Great, it works!!!
Thank you so much for your time and patience. 
BTW, in the results, it seems that it blasts the primers to the human genome. 
Is it possible to add C elegans to the blast option? 

Thank you again.

**Comment by tjakobi** [comment]
Circtools employs predefined BLAST databases from the NCBI. If I can locate a specific database for C.elegans I am happy to add it, too.
