### ISSUE TITLE
Integration of the alternative exon usage script

### ISSUE THREAD

**Issue by tjakobi** [dieterich-lab/circtools#6]

**Comment by tjakobi** [comment]
The problem of incorrect plots generated by the `ggplot` part of the script persists. The problem is related to inconsistent exon start-stop coordinates between `reducedExon` and `exonValues`. The issue only occurs in the plotting part and does not seem to influence the generation of BED tracks by the script.

Until we find a final solution we should either prepare a note for users regarding the issue or disable the plotting function entirely.

**Comment by CDieterich** [comment]
Don't waste your time on ggplot.
BEDGRAPH and BED tracks should be fine for output / visualization.

**Comment by tjakobi** [comment]
Yeah, that's what I meant.

I'll disable the plotting function for now since most of the plots won't show up correctly anyway.
