### ISSUE TITLE
question on grouping for circtest

### ISSUE THREAD

**Issue by idotu** [dieterich-lab/circtools#68]
Hi,
I'm sorry but I'm not quite sure I understand the -g flag. If I have 2 conditions with 3 samples each and they are positioned like this: CondA_sample1 CondA_sample2 CondA_sample3 CondB_sample1 CondB_sample2 CondB_sample3, how is it supposed to be? I'm using -l CondA,CondB -g 1,1,1,2,2,2 -r 3. Is it correct?

Many thanks!!!!

**Comment by tjakobi** [comment]
Dear @idotu ,

You're using the parameters correct, that's how I thought it would be most convenient. 

Cheers,
Tobias
