### ISSUE TITLE
Error installing circtools on Mac OSX due to no wget

### ISSUE THREAD

**Issue by skambha6** [dieterich-lab/circtools#77]
I am unable to directly install circtools on Mac OSX because osx does not come with wget pre-installed (user-end workaround possible by installing wget on osx using homebrew)

Command used: pip3 install circtools --user
Error message:
-bash: wget: command not found

 - OS: Mac OSX 10.11.6

**Comment by tjakobi** [comment]
As a fix I will implement a OS switch for MacOS and then use `curl` instead, which is part of the default MacOS install.

**Comment by tjakobi** [comment]
Dear @skambha6, 

please test the installation routine again on
