### ISSUE TITLE
Error in dplyr/rlang version using primex module

### ISSUE THREAD

**Issue by skambha6** [dieterich-lab/circtools#79]
When using Primex module, I get the error message copied below. Appears to be due to not having the fully updated version of dplyr which may be related to which versions of the R dependencies/packages that are installed during circtools installation.

circtools primex -d 01_detect/CircCoordinates -f ../Mus_musculus.GRCm38.dna.primary_assembly.fa -g ../Mus_musculus.GRCm38.90.gtf -O mm -G Ryr2 -T "Ryr2 primer"

Error message:
Error in mutate_impl(.data, dots) : 
  Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.
Calls: %>% ... as.data.frame -> mutate -> mutate.tbl_df -> mutate_impl -> .Call

-OSX 10.11.6
-R 3.3.1

**Comment by tjakobi** [comment]
This issues is caused by an outdated version of `dplyr`. 

`dplyr` has to be updated to >=0.7.7. 

See also: https://github.com/r-lib/rlang/issues/674

Has to be fixed possibly by forcing an update of `dplyr` during install.
