### ISSUE TITLE
primex not intron-aware? 

### ISSUE THREAD

**Issue by daaaaande** [dieterich-lab/circtools#83]
for me it seems like primex likes to design primers inside introns that are not part of the circRNA, but are between the exons in the genome sequence:

circRNA candidate : hsa_circ_0077535 : chr6:106727535-106740981 strand - 
is there an option or flag i did not set? 

when running circtools primex with the following parameters:
hg19 as reference, -O hs , gtf reference from ensembl, tried with and without -j r parameter

circRNAs_candidates.bed:
chr6	106727535	106740981	ATG5	ATG5	-

the output generated includes mostly (on the forward side) primers inside introns that are part of the reference genome sequence, yet will not be part of the circRNA in question

system information: 
circtools version: 1.1.0.8
Ubuntu 5.0.0-29-generic #31-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux

**Comment by tjakobi** [comment]
Hi @daaaaande,

primex shouldn't do anything in introns - at least not by design.

What Ensembl annotation version are you using and where is the hg19 reference file from?

Cheers,
Tobias

**Comment by daaaaande** [comment]
Hi @tjakobi ,
first of all thanks for the quick reply!

**Comment by tjakobi** [comment]
Hi @daaaaande,

I would use FASTA and annotation from the the same source. Right now I feel like you are mixing the hg19 fasta with hg38 annotation (Ensembl).

I would go with
- Annotation: ftp://ftp.ensembl.org/pub/release-98/gtf/homo_sapiens/Homo_sapiens.GRCh38.98.gtf.gz
- Sequence: ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

Those definitely fit together.

Cheers,
Tobias
